### ISSUE TITLE
Release interim version to Maven Central

### ISSUE THREAD

**Issue by kibertoad** [jfree/jfreechart#32]
Latest version on Maven Central is almost two years old by now... I do understand that this will be released when it will be ready, but can we have a beta or RC interim release published to Maven Central repo meanwhile? Consuming snapshots is really inconvenient.

**Comment by altavir** [comment]
Yes! Please, please please! Version 1.5 in particular.

**Comment by jfree** [comment]
I've learned not to make promises, but it is my *intention* to get a new JFreeChart release done before the end of 2016.

**Comment by tomas-pluskal** [comment]
There is a number of pull requests that have been waiting for a long time. If David is too busy to maintain the project, how about extending the admin rights to other people, so they could prepare and deploy releases, too?

**Comment by jfree** [comment]
So obviously I missed end of 2016, but I am making some progress on the new release.  :-)

**Comment by kibertoad** [comment]
Can we still have an interim non-final Maven-released version, then?

**Comment by jfree** [comment]
Yes, working on it.

**Comment by Legiew** [comment]
Any progress here? I noticed in the readme a release date for the 1.0.20 version (18-Feb-2017).
Would like to have the javafx improvements for a project without building it by myself. Would be great!

**Comment by jfree** [comment]
Yes, making some progress.  I'm moving the JavaFX support classes to a separate project (not visible yet), and branching the Git repo so that 1.0.20 will be released from a v1.0.x branch and a new release (1.5.0) with JCommon classes consolidated and this will be the base version for the JavaFX support.

**Comment by jfree** [comment]
I pushed the work-in-progress and made the jfreechart-fx repo visible.  Please feel free to check that you can build the JFreeChart-FX module with JFreeChart 1.5.0 (master branch) while I continue cleaning it up for release.  I will also release JFreeChart 1.0.20 (Swing support only) from the v1.0.x branch when everything is ready.

**Comment by Legiew** [comment]
Ok got it working, but:

- test: org.jfree.data.time.MonthTest testParseMonth test3 failed (see #33 and #34 )
- a few imports/classnames in the fx project were wrong (mostly import org.jfree.ui.xxx > import org.jfree.chart.ui.xxx) you will notice them if you try to execute the fx demos

Great to see the progress. Thumbs up for the good work David!

**Comment by jfree** [comment]
Fixed the imports.  Will look at the tests later.

**Comment by Legiew** [comment]
Hey,

I tried again with the latest sources:

- The unit test (testParseMonth) is still failing for me (I have german local settings)
- In the fx project two methods in PieChartFXDemo1 have to be renamed from xxxBasexxx to xxxDefaultxxx

Beside these two issues the build and the demos are running successfully.

**Comment by jfree** [comment]
Closing this since JFreeChart 1.5.0 and JFreeChart-FX 1.0.0 have been released, finally.
